### ISSUE TITLE
Cant install dependences using 'make build' 

### ISSUE THREAD

**Issue by alulaxp** [CodelyTV/php-ddd-example#252]
I get this error when trying to install dependences. Im using wsl, Docker is running and i also tried 'docker build'

Am I missing something? 

------
 > [ 9/13] RUN sh /root/install-rabbitmq.sh:
#14 0.858 Cloning into 'php-amqp'...
: No such file or directorybitmq.sh: cd: line 2: can't cd to php-amqp
: not foundroot/install-rabbitmq.sh: line 3: phpize
: not foundroot/install-rabbitmq.sh: line 4: ./configure
: not foundroot/install-rabbitmq.sh: line 5: make
'.  Stop. make: *** No rule to make target 'install
------
executor failed running [/bin/sh -c sh /root/install-rabbitmq.sh]: exit code: 2      
ERROR: Service 'backoffice_backend_php' failed to build
make: *** [Makefile:72: start] Error 1

![image](https://user-images.githubusercontent.com/67409196/117257316-0b951800-ae4c-11eb-94eb-dc80ca54b0d6.png)

**Comment by JavierCane** [comment]
Taking a look!

**Comment by JavierCane** [comment]
PR regarding AMQP errors merged 🎉

More info: https://github.com/CodelyTV/php-ddd-example/pull/253

You should be able to follow [the repository ReadMe instructions on how to setup your development environment](https://github.com/CodelyTV/php-ddd-example#-environment-setup) successfully 😊

**Comment by alulaxp** [comment]
thanks Javi!

**Comment by snamor** [comment]
I know it's old, but faced the same error recently. 

The reason was that I had git configured with `autocrlf = true`. This led to line breaks being changed to CRLF (windows style). Once this was executed in WSL, it lead to these errors. 

To fix it, i changed the `.sh` files line endings to LF, and it worked as it should. 

Hope this helps someone that has the same issue!
